# Generated by Django 5.2.8 on 2025-11-29 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sistema_alerta_estacionamento', 'Alerta de Estacionamento'), ('reserva_confirmada', 'Reserva Confirmada'), ('alerta_saida', 'Alerta de Saída Manual'), ('sistema_erro', 'Erro do Sistema'), ('motorista_incorreto', 'Motorista Incorreto'), ('info_geral', 'Informação Geral'), ('alerta_seguranca', 'Alerta de Segurança')], default='info_geral', max_length=50, verbose_name='Tipo de Notificação')),
                ('motivo', models.TextField(verbose_name='Motivo/Descrição')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('vaga_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Vaga (Firestore)')),
                ('vaga_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Vaga')),
                ('placa', models.CharField(blank=True, max_length=15, null=True, verbose_name='Placa do Veículo')),
                ('usuario_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Usuário (Firestore)')),
                ('estacionamento_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Estacionamento (Firestore)')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict, verbose_name='Dados Adicionais (JSON)')),
            ],
            options={
                'verbose_name': 'Notificação Admin',
                'verbose_name_plural': 'Notificações Admin',
                'db_table': 'notificacoes_admin',
                'ordering': ['-timestamp'],
            },
        ),
    ]
